# Generated by Django 4.2.20 on 2025-04-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_alter_contacts_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelTable(
            name='news',
            table='main_news',
        ),
    ]
