# Generated by Django 4.2.20 on 2025-05-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_news_options_alter_news_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=500)),
                ('photo', models.ImageField(upload_to='news/')),
            ],
            options={
                'db_table': 'main_specials',
                'ordering': ('title', 'desc', 'photo'),
            },
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
