# Generated by Django 4.2.20 on 2025-05-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_specials_delete_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specials',
            name='photo',
            field=models.ImageField(upload_to='specials/'),
        ),
    ]
