# Generated by Django 4.2.20 on 2025-05-02 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_specials_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specials',
            options={},
        ),
        migrations.AlterModelTable(
            name='specials',
            table=None,
        ),
    ]
