# Generated by Django 4.2.20 on 2025-05-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_specials_options_alter_specials_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='specials',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='specials',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
